config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :yachts do
    resources :bookings, only: :create
  end
  get "/dashboard", to: "pages#dashboard"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="" id="footer">
  <div class="card-body d-flex justify-content-between align-items-center p-3">
    <div class="text-center mx-3 d-flex justify-between gap-3 align-items-center text-white">
      <p><strong>Explore</strong></p>
      <p><%= link_to "Become a Seller", new_yacht_path, class: "text-decoration-none" %></p>
      <p><a href="#">Partner Voice</a></p>
      <p><a href="#">Leave a Review</a></p>
    </div>
    <div class="d-flex justify-content-center align-items-center text-center mx-3">
      <p class="ps-2">
        <a href="#"><i class="fa-brands fa-facebook"></i></a>
      </p>
      <p class="ps-2">
        <a href="#"><i class="fa-brands fa-instagram"></i></a>
      </p>
      <p class="ps-2">
        <a href="#"><i class="fa-brands fa-square-x-twitter"></i></a>
      </p>
      <p class="ps-2">
        <a href="#"><i class="fa-brands fa-tiktok"></i></a>
      </p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon py-2">
  <div class="container">
    <div>
      <%= link_to root_path, class: "navbar-brand d-flex flex-row m-0" do %>
        <%= image_tag "logo.png", class: "p-0 mx-2", style: "height: 50px; width: 50px; border-radius: 50%;" %>
        <h2 class="grape-nuts-font d-flex align-items-center m-0">Blue Horizon</h2>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Yachts", yachts_path, class: "nav-link" %>
        </li>
        <li class="nav-item active d-sm-none">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item active d-sm-none">
          <%= link_to "Add a Yacht", new_yacht_path, class: "nav-link" %>
        </li>
        <li class="nav-item active d-sm-none">
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown d-flex align-items-center">
          <button class="nav-button rounded-3 d-none d-sm-block" type="button" data-bs-toggle="dropdown" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="dropdown-menu dropdown-menu-end navbar-expand-sm" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Add a Yacht", new_yacht_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>