config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :yachts do
    resources :bookings, only: :create
  end
  get "/dashboard", to: "pages#dashboard"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/_info_window.html.erb
<div class="container">
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class="img-name">
      <% if yacht.photo.attached? %>
        <%= cl_image_tag(yacht.photo.key, class:"card-img-top rounded-4") %>
      <% end %>
    </div>

    <div>
      <h4 class="my-2"><%= yacht.name.capitalize %></h4>
      <p class="mb-0"><%= yacht.address %></p>
      <p class="mb-0">£<%= yacht.price %> per day</p>
    </div>

  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col">
      <div class="p-5">
        <h1 class="grape-nuts-font">Welcome,</h1>
        <h1 class="grape-nuts-font"><%= current_user.name.titleize %></h1>
      </div>
    </div>


    <div class="col mb-3">
      <div class="container dashboard-section-background px-4 rounded-5 d-flex flex-column justify-content-center">
        <div class="section-header-background text-center rounded-4 mt-4 mb-3">
          <h3 class="m-0 grape-nuts-font">Your Yachts</h3>
        </div>
        <div class="row">
          <% if current_user.yachts.length > 0 %>
            <% current_user.yachts.each do |yacht| %>
                <%= link_to yacht_path(yacht), class: "text-decoration-none text-black d-flex justify-content-center" do %>
                  <div class="card rounded-4 mb-4">
                    <% if yacht.photo.attached? %>
                      <%= cl_image_tag(yacht.photo.key, class:"card-img-top rounded-top-4", style:"width: 300px; height: 200px;") %>
                    <% end %>
                      <div class="card-body d-flex flex-row justify-content-between align-items-center">
                          <div>
                            <h5 class="card-title mb-0"><%= yacht.name.titleize %></h5>
                            <p class="card-title mb-0"><%= yacht.address %></p>
                          </div>
                          <div>
                            <h6 class="mb-0">£<%= yacht.price %></h6>
                            <p class="mb-0">per day</p>
                          </div>
                      </div>
                  </div>
                <% end %>
            <% end %>
          <% else %>
            <p>You don't have any yachts yet</p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col mb-3">
      <div class="container dashboard-section-background px-4 rounded-5 d-flex flex-column justify-content-center">
        <div class="section-header-background text-center rounded-4 mt-4 mb-3">
          <h3 class="m-0 grape-nuts-font">Your Bookings</h3>
        </div>
        <div class="row">
          <% if @user_bookings.length > 0 %>
            <% @user_bookings.each do |booking| %>
              <div class="d-flex flex-row justify-content-center">
                <div class="card mb-4 rounded-5">
                  <div class="card-body">
                    <div class="d-flex flex-row justify-content-between align-items-center" style="width: 335px; height: 205px;">
                      <div class="img-name w-50">
                        <% if booking.yacht.photo.attached? %>
                          <%= cl_image_tag(booking.yacht.photo.key, class:"card-img-top rounded-4") %>
                        <% end %>
                        <div>
                          <h5 class="card-title mb-0 pt-2"><%= booking.yacht.name.titleize %></h5>
                          <p class="card-title mb-0"><%= booking.yacht.address %></p>
                        </div>
                      </div>

                      <div class="dates-price text-center w-50">
                        <div class="dates">
                          <p class="mb-1">Dates:</p>
                          <i><%= booking.start_date.strftime("%b %e, %Y") %></i>
                          <br>
                          -
                          <br>
                          <i><%= booking.end_date.strftime("%b %e, %Y") %></i>
                        </div>
                        <p class="mb-0 mt-3">Total: £<%= booking.price %></p>
                      </div>

                    </div>

                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <p>You don't have any bookings yet</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_url('riis-riiiis-XS5mxDrurQg-unsplash.jpg') %>')" alt="Homepage_Blue_Horizon">
  <div class="container d-flex justify-content-between align-items-center position-relative">
    <div></div>
    <div class="text-center position-absolute top-50 start-50 translate-middle">
      <h1><%= link_to "View All Yachts", yachts_path, class: "btn btn-info btn-lg rounded-4" %></h1>
    </div>
    <div id= "title">
      <h1 id= "title"><strong>Blue Horizon</strong></h1><br>
      <p>Serene Waters,<br>
      Exclusive Adventures</p>
    </div>
  </div>
</div>





<div class="container text-center">
  <h1 class="my-5" id= "yacht_home" >Our Yachts</h1>
  <div class="row g-5 d-flex justify-content-between">
    <% @threeYachts.each do |yacht| %>
      <div class="col-xl-3 col-lg-3 col-md-4 col-sm-12">
        <%= link_to yacht_path(yacht), class: "text-decoration-none text-black" do %>
          <div class="card rounded-3 h-100" style="width: 18rem;">
            <% if yacht.photo.attached? %>
              <%= cl_image_tag(yacht.photo.key, class:"card-img-top img-fluid") %>
            <% end %>
            <div class="card-body d-flex flex-row justify-content-between align-items-center">
              <div class="text-start">
                <h5 class="card-title mb-0"><%= yacht.name.titleize %></h5>
                <p class="card-title mb-0"><%= yacht.address %></p>
              </div>
              <div>
                <h6 class="mb-0">£<%= yacht.price %></h6>
                <p class="mb-0">per day</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

<div class="container d-flex flex-row justify-content-center align-items-center my-5">
  <div class="rounded-4" style="width: 100%; height: 400px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>